<?php

$pages[0] = new page();
$pages[0]->link_text = 'Moi moi';
$pages[0]->square_image = "matkalogo.png";
$pages[0]->content_title = "ja vielä moi";
//$pages[0]->content_image = "";
$pages[0]->content_page = 'empty.inc';
$pages[0]->link_in_sidebar = "yes";

$pages[1] = new page();
$pages[1]->link_text = 'Totanoin niin';
$pages[1]->content_title = "Joopa joo";
$pages[1]->content_page = 'empty.inc';
$pages[1]->link_in_sidebar = "yes";

$pages[2] = new page();
$pages[2]->link_text = 'Plaah plaah';
$pages[2]->content_page = 'empty.inc';
$pages[2]->link_in_sidebar = "yes";

$pages[3] = new page();
$pages[3]->ext_link = "#";
$pages[3]->link_text = "externallink.fi";

$pages[4] = new page();

$pages[5] = new page();

$pages[6] = new page();

$pages[7] = new page();

$pages[8] = new page();

$pages[9] = new page();


?>
