	
	<section class="billboard">
			<div class="wrapper">
				<div class="caption">
                                        <p>HIFK D2 2005 -
                                        Kanada/USA 2017</p>
				</div>
			</div>
	</section><!--  End Billboard  -->

	<section class="info">

		<div class="info_pic">
		</div>
		<div class="info_details info_details2">
			<h3>HIFK D2 Juniorit</h3>
			<p>
                           Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu pariatur, Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
			</p>
                        <a href=".?0">Lue lisää <span>→</span></a>     
		</div>
		
		<div class="info_details">
			<h3>Turnausmatka Kanadaan ja Yhdysvaltoihin</h3>
			<p>
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu pariatur, Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
			</p>
                        <a href=".?1">Lue lisää <span>→</span></a>
		</div>
        <div class="info_pic2">
		</div>
	
		<div class="info_pic3">
		</div>
		<div class="info_details">
			<h3>Kiinnoistaisko sinua tukea meitä?</h3>
			<p>
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu pariatur, Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
			</p>
                        <a href=".?2">Lue lisää <span>→</span></a>
		</div>
		
	</section><!--  End Info  -->
    
	<section class="testimonials wrapper">

		<span class="sep_line sep_top">
		</span>
		<!--<h2>Testimonials</h2>-->
		<div class="testi_slider" id="tslider">
			<div class="t">
		            <p>Mahtava kaksi viikkoa tulossa! Nää on ihan huippu jätkiä ja aina innoissaan hallilla ja peleissä. Tosi upeaa lähteä reissuun ja saada elämys pojille
			    </p>
                            <p class="author">Teppo Teikäläinen - Joukkueenjohtaja</p>   
			</div>
			<div class="t">
			    <p>
                            Rennosti lähetään katsomaan miltä peli näyttää rapakon tuolla puolen, kovaa mennään mutta pilke silmäkulmassa!
			    </p>
                            <p class="author">Matti Meikäläinen - Valmentaja</p>
			</div>
			<div class="t">
		    	<p>Makee lähtee pelaa jenkkeihin! NHL-matsi pitää nähdä myös!
			    </p> 
                            <p class="author">Timo Sentteri - Kapteeni</p>
			</div>
		</div>
		<div id="t_navigation"></div>
		<span class="sep_line sep_bottom"></span>

	</section> <!--  End Testimonials  -->

    <section class="features">

		<div class="wrapper">
				<div class="feature">
					<div class="ficon">
						<img src="img/pages/company1.jpg" alt="">
					</div>
					<div class="details_exp">
						<h3>Pizza-online</h3>
						<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu pariatur,
						</p>
						<a href=".?1">Lue lisää...<span>→</span></a>
					</div>
				</div>
				<div class="feature">
					<div class="ficon">
						<img src="img/pages/company2.jpg" alt="">
					</div>
					<div class="details_exp">
						<h3>Nollasähkö Oy</h3>
						
                                                <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu pariatur,
                                                </p>
                                                <a href=".?2">Lue lisää...<span>→</span></a>
					</div>
				</div>
				<div class="feature">
					<div class="ficon">
						<img src="img/pages/company3.jpg" alt="">
					</div>
					<div class="details_exp">
						<h3>CyberTalo Ltd</h3>

                                                <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu pariatur,
                                                </p>
						<!--<a href=".?3">Lue lisää...<span>→</span></a>-->
					</div>
				</div>

			</div>

	</section><!--  End Features  -->
