	
	<section class="billboard">
			<div class="wrapper">
				<div class="caption">
				<p>HIFK 05 - Pohjois-Amerikka 2017</p>
                                </div>
			</div>
	</section><!--  End Billboard  -->

	<section class="info">

		<div class="info_pic">
		</div>
		<div class="info_details info_details2">
			<?php echo "<h3>" . $pages[0]->link_text . "</h3>"?>
			<p>
Joukkue perustettiin keväällä 2012. Joukkueessa aloitti kiekkokoulun jälkeen reilun 40 pelaajan ryhmä innokkaita kiekkoilijan alkuja. Tähän mennessä pojilla on takana siis neljän ja puolen kauden mittainen rupeama kiekkoilun parissa. 
			</p>
                        <a href=".?0">Lue lisää <span>→</span></a>     
		</div>
		
		<div class="info_details">
                        <?php echo "<h3>" . $pages[1]->link_text . "</h3>"?>
			<p>
Kauden 2017 - 18 kohokohdaksi on suunniteltu Pohjois-Amerikkaan toteutettava turnaus- ja pelimatka. Suunnitelmana on tutustua jääkiekon emämaan Kanadan jääkiekkokulttuuriin ja osallistua Toronton alueella pelattavaan isoon kansainväliseen jääkiekkoturnaukseen.
			</p>
                        <a href=".?1">Lue lisää <span>→</span></a>
		</div>
        <div class="info_pic2">
		</div>
	
		<div class="info_pic3">
		</div>
		<div class="info_details">
			<?php echo "<h3>" . $pages[2]->link_text . "</h3>"?>
			<p>
Nyt sinulla tai edustamallasi yrityksellä on erinomainen mahdollisuus tukea junioriurheilua ja -kiekkoilua! Aktiivisella varainhankinnalla pyrimme mahdollistamaan turnaus- ja pelireissuun osallistumisen tasapuolisesti kaikille joukkueen pelaajille. 
			</p>
                        <a href=".?2">Lue lisää <span>→</span></a>
		</div>
		
	</section><!--  End Info  -->
    
	<section class="testimonials wrapper">

		<span class="sep_line sep_top">
		</span>
		<!--<h2>Testimonials</h2>-->
		<div class="testi_slider" id="tslider">
			<div class="t">
                            <p>Hienoa päästä pelaamaan, toivottavasti vedetään hyvin! NHL-matsi ois makee nähdä!</p><p class="author">Aaro #23</p>   
			</div>
<!--
			<div class="t">
		            <p>Kommentti #2</p>
                            <p class="author">Kommentoija #2</p>
			</div>
			<div class="t">
			    <p>Kommentti #3</p> 
                            <p class="author">Kommentoija #3</p>
			</div>
-->
		</div>
		<div id="t_navigation"></div>
		<span class="sep_line sep_bottom"></span>

	</section> <!--  End Testimonials  -->

    <section class="features">

		<div class="wrapper">
				<div class="feature">
					<div class="ficon">
						<img src="img/sponsors/hedmanpartners.jpg" alt="">
					</div>
				</div>
                                <div class="feature">
                                        <div class="ficon">
                                                <img src="img/sponsors/TEHOSport.png" alt="">
                                        </div>
                                </div>
                                <div class="feature">
                                        <div class="ficon">
                                                <img src="img/sponsors/SBIpartner.jpg" alt="">
                                        </div>
                                </div>
                                <div class="feature">
                                        <div class="ficon">
                                                <img src="img/sponsors/telva80.jpg" alt="">
                                        </div>
                                </div>
		</div>

	</section><!--  End Features  -->
