			

<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/fi_FI/sdk.js#xfbml=1&version=v2.8";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="column_left">
<h2>Joukkue</h2>
<p>
Joukkue on osa HIFK Juniors -perhettä, jossa ovat mukana joukkueet pienimmistä G -junioreista aina A
-junioreihin saakka. IFK:ssa kehitetään pelaajia sekä kaukalossa että sen ulkopuolella. Tavoitteena on edesauttaa pelaajien laaja-alaista kasvua ja kehitystä sekä kehittää lasten ja nuorten asennetta siten, että se tukisi heidän menestymistään niin koulussa, kaukalossa kuin muussakin elämässä aktiivisen kiekkouran jälkeen.
<br/>
<br/>
05 -joukkue perustettiin keväällä 2012. Joukkueessa aloitti kiekkokoulun jälkeen reilun 40 pelaajan ryhmä innokkaita kiekkoilijan alkuja. Tähän mennessä pojilla on takana noin viiden - kuuden vuoden mittainen rupeama kiekkoilun parissa. Muutama poika on matkan varrella vaihtunut tai tullut joukkueeseen lisää, mutta suurin osa pojista on ollut alusta alkaen mukana. Kehitystä ja hauskaa tekemistä on koettuna jo siis reilu annos, ja intoa kiekkoiluun riittää edelleen!
</p>
<h2>Kausi 2016-17</h2>
<p>
Joukkueen koko tällä hetkellä noin 30 poikaa. Innokkaat pojat ovat kehittyneet suurin askelin kiekkoilijan urallaan, 
ja muutos ensimmäisistä vuosista on suuri. Tällä kaudella osallistumme kahdella joukkueella jääkiekkoliiton eteläisen 
alueen sarjaan, pelaamme harjoitusotteluita ja harjoittelemme noin neljä kertaa viikossa.
</p>
<h2>Seuraa meitä</h2>
<p>
Joukkueeseen ja sen toimintaan voi tutustua tarkemmin oheisten linkkien kautta:
<br/><br/>
<a href="http://www.hifkjrs.com/jengit2016/2016_jengi.php?jengi=e05">Joukkueen sivut</a><br/>
<a href="https://www.facebook.com/hifk05">Facebook</a>
</p>
</div>
<div class="column_right">
 <div class="fb-page" data-href="https://www.facebook.com/hifk05/" 
data-tabs="timeline" data-width="350" data-height="700" 
data-small-header="true" data-adapt-container-width="false" 
data-hide-cover="false" data-show-facepile="false">

<blockquote cite="https://www.facebook.com/hifk05/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/hifk05/">HIFK E05</a></blockquote></div>
		
</div>
