<div>
<div class="column_left">
<h2>Kanada - Kansainvälinen jääkiekkoturnaus</h2>
<p>
Kauden 2017 - 18 kohokohdaksi on suunniteltu Pohjois-Amerikkaan toteutettava turnaus- ja pelimatka. 
Suunnitelmana on tutustua jääkiekon emämaan Kanadan jääkiekkokulttuuriin ja osallistua Toronton alueella pelattavaan isoon kansainväliseen jääkiekkoturnaukseen. 
Samalla tulee tutuksi jo lentävänä lauseena liikkuva sanonta ”Kanadassa jääkiekko on jotain paljon suurempaa kuin missään muualla, 
kaikki puhuvat siitä ja kaikki tietävät siitä kaiken”. 
Kiekkoilun lisäksi turnauksen aikana tutustutaan myös kanadalaiseen kulttuuriin ja perheisiin. 
Jääkiekon syntyhistoriaan ja kuuluisiin pelaajiin päästään tutustumaan myös välttämättömässä vierailukohteessa Hockey Hall of Fame:ssä.

<br/>
<br/><a href="https://www.hhof.com">Hockey Hall of Fame</a>
<br/>
</p>
</div>
<div class="column_right">
<img src="img/pages/turnauslogo.jpg">
</div>
</div>
<div>
<div class="column_left">
<h2>Ystävyysvierailu Minnesotaan</h2>
<p>
Turnauksen jälkeen suuntaamme vielä Yhdysvaltojen puolelle Minnesotan alueelle, 
jossa vierailemme Suomessa vierailulla käyneen Northfield Hockey:n tuttujen pelaajien luona. 
Minnesotan alueella suomalaiset ja suomalainen kulttuuri on jo historiallisesti tunnettu juttu, 
useat Minnesotassa pelaavat suomalaiset ammattikiekkoilijat lisäävät Suomen tunnettavuutta entisestään. 
Aikataulujen osuessa kohdalleen käymme tutustumassa matkan aikana myös näiden kiekkoilijoiden edesottamuksiin 
Xcel Energy Center:issä. Noin kahden viikon reissussa on näin ollen paljon nähtävää, tutustuttavaa ja koettavaa! 
Todennäköisesti pojat muistavat tämän ikimuistoisen reissun vielä vuosienkin päästä. 

<br/>
<br/><a href="http://www.northfieldhockey.net/page/show/101512-nha-home-page">Northfield Hockey</a>
<br/><a href="https://www.google.fi/maps/place/Northfield+Ice+Arena/@44.4464671,-93.1782393,17z/data=!3m1!4b1!4m5!3m4!1s0x87f653e1bae83715:0x54ab16bd236fecd3!8m2!3d44.4464671!4d-93.1760506">Sijainti</a>
</p>
</div>
<div class="column_right">
<img src="img/pages/minnesotahockey.png">
</div>
</div>

