<div class="column_left">
<h2>Tue junioriurheilua ja -kiekkoilua</h2>
<p>				
Nyt sinulla tai edustamallasi yrityksellä on erinomainen mahdollisuus tukea junioriurheilua ja -kiekkoilua! 
Aktiivisella varainhankinnalla pyrimme mahdollistamaan turnaus- ja pelireissuun osallistumisen tasapuolisesti 
kaikille joukkueen pelaajille. 
</p>
<h2>Monia tukimahdollisuuksia</h2>
<p>
Tukimahdollisuuksia on monia, mutta yksinkertaisimmillaan sponsoroit joukkuetta valitsemallasi summalla. 
Sinulla on myös halutessasi mahdollisuus saada näkyvyyttä joukkueen turnausreissussa käyttämissä pelipaidoissa 
tai tällä sivustolla. Olemme myös avoimia muillekin hyville yhteistyöehdotuksille!
</p>
<h2>Ota yhteyttä</h2>
<p>
Mikäli kiinnostuit tukimahdollisuudesta, niin ota yhteyttä. Autamme sinua mielellämme asian kanssa. 

<br/>
<br/>
info<img src="img/pages/at.jpg" alt='@'>hifk05turnausmatka<img src="img/pages/dot.jpg" alt='.'>net 
</p>
</div>
<div class="column_right sponsors">
<h2>Yhteistyökumppanimme</h2>
<a href="http://www.hedman-attorneys.com" target="_sponsors_">Hedman Partners</a>
</div>
